-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE FROM MEMBER_PROFILE AS P INNER JOIN REST_REVIEW AS R ON P.MEMBER_ID = R.MEMBER_ID WHERE P.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1) ORDER BY REVIEW_DATE, REVIEW_TEXT;
#SELECT P.MEMBER_NAME, COUNT(R.MEMBER_ID) FROM MEMBER_PROFILE AS P INNER JOIN REST_REVIEW AS R ON P.MEMBER_ID = R.MEMBER_ID GROUP BY R.MEMBER_ID;
# SELECT CAST(CURRENT_TIMESTAMP AS DATE);
# CAST(DATE(REST_REVIEW.REVIEW_DATE) AS REVIEW_DATE) 
# MEMBER_NAME, REVIEW_TEXT, DATE(REVIEW_DATE) AS REVIEW_DATE