-- 코드를 입
SELECT B.CATEGORY, SUM(A.TOTAL_SALES) AS TOTAL_SALES FROM (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES FROM BOOK_SALES GROUP BY BOOK_ID, SALES_DATE HAVING DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS A INNER JOIN (SELECT BOOK_ID, CATEGORY FROM BOOK) AS B ON A.BOOK_ID = B.BOOK_ID GROUP BY B.CATEGORY ORDER BY B.CATEGORY ASC;
