-- 코드를 입력하세요
-- SELECT A.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * A.AMOUNT) AS TOTAL_SALES FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, DATE_FORMAT(PRODUCE_DATE, '%Y-%m') AS PRODUCE_DATE FROM FOOD_ORDER GROUP BY PRODUCT_ID HAVING PRODUCE_DATE = '2022-05') AS A INNER JOIN FOOD_PRODUCT AS P ON A.PRODUCT_ID = P.PRODUCT_ID ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;

SELECT P.PRODUCT_ID, P.PRODUCT_NAME,
(P.PRICE * SUM(O.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P INNER JOIN FOOD_ORDER AS O 
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID


-- 17, 2200
